name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests with Allure
      - name: Run Playwright tests
        run: |
          # Install allure-playwright if not installed
          npm install -D allure-playwright
          
          # Run the tests with Allure reporter
          npx playwright test --reporter=list,allure-playwright

          # Generate the Allure report
          npx allure generate ./allure-results --clean || echo "Allure report generation failed"

      # Step 6: Upload Playwright Test Artifacts (Allure Results)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Clone the gh-pages branch (or create it if it doesn't exist)
        run: |
          git clone --branch gh-pages https://github.com/EugeneQADev/pw-allure.git gh-pages || git clone https://github.com/EugeneQADev/pw-allure.git gh-pages

      - name: Copy Allure Report to gh-pages
        run: |
          if [ -d "allure-report" ]; then
            echo "Allure report directory exists, copying files..."
            cp -r allure-report/* gh-pages/
          else
            echo "Allure report directory does not exist!"
          fi

      - name: Commit and Push changes to gh-pages
        run: |
          cd gh-pages
          git add .
          git commit -m "Update Allure report" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/EugeneQADev/pw-allure.git gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}