name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests with Allure
      - name: Run Playwright tests
        run: |
          # Install allure-playwright if not installed
          npm install -D allure-playwright
          
          # Run the tests
          npx playwright test --reporter=list,allure-playwright
          
          # Generate the Allure report
          npx allure generate ./allure-results --clean

      # Step 6: Upload Playwright Test Artifacts (Allure Results)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30