name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests with Allure
      - name: Run Playwright tests
        run: |
          # Install allure-playwright if not installed
          npm install -D allure-playwright
          
          # Run the tests
          npx playwright test --reporter=list,allure-playwright
          
          # Generate the Allure report
          npx allure generate ./allure-results --clean
          
          # Show the allure-report folder content to check if report is generated
          ls -la allure-report

      # Step 6: Upload Playwright Test Artifacts (Allure Results)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

  # Add a new job to deploy Allure report to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy Allure Report to GitHub Pages
        run: |
          # Configure Git
          git config --global user.email "avocodejames2@gmail.com"
          git config --global user.name "Evhenii"

          # Clone the gh-pages branch (or create it if it doesn't exist)
          git clone --branch gh-pages https://github.com/EugeneQADev/pw-allure.git gh-pages || git clone https://github.com/EugeneQADev/pw-allure.git gh-pages

          # Check if the allure-report directory exists before copying
          if [ -d "allure-report" ]; then
            echo "Allure report directory exists, copying files..."
            cp -r allure-report/* gh-pages/
          else
            echo "Allure report directory does not exist!"
          fi

          # Commit and push changes to the gh-pages branch
          cd gh-pages
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages